FROM node:22-alpine

# Instala Chromium para rodar testes do Angular (Karma)
RUN apk add --no-cache chromium

# Define variável de ambiente para o Chrome Binário
ENV CHROME_BIN=/usr/bin/chromium-browser

WORKDIR /app
COPY package*.json ./

# Instala CLI globalmente para garantir execução de comandos ng
RUN npm install -g @angular/cli

RUN npm install
COPY . .
EXPOSE 4200
CMD ["npm","run","start"]
