FROM node:22-alpine

RUN apk add --no-cache chromium xvfb

# Define variável de ambiente para o Chrome Binário
ENV CHROME_BIN=/usr/bin/chromium-browser

WORKDIR /app
COPY package*.json ./

RUN npm install -g @angular/cli

RUN npm install \
 && npx cypress install
COPY . .
EXPOSE 4200
CMD ["npm","run","start"]
