services:
  frontend-e2e:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start
    ports:
      # Permite acompanhar a aplicação sob teste no navegador host (http://localhost:4200)
      - "4200:4200"
    volumes:
      - .:/app
      - node_modules_e2e:/app/node_modules
    depends_on:
      - json-server-test-e2e

  json-server-test-e2e:
    build:
      context: ./json-server
      dockerfile: Dockerfile
    volumes:
      # Usa banco de dados de teste para não sujar dados de desenvolvimento
      - ./json-server/db.test.json:/app/db.json

  cypress-e2e:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - frontend-e2e
    environment:
      # Sobrescreve baseUrl apenas dentro do container do Cypress
      - CYPRESS_baseUrl=http://frontend-e2e:4200
    volumes:
      - .:/app
      - node_modules_e2e:/app/node_modules
    command: npm run cypress:run

volumes:
  node_modules_e2e:


